-- 0129 — APPLIQUÉE EN LIVE via MCP le 15/08/2026 (stub de référence).
-- CORRECTIF de 0128 : `affaires.tvac_centimes` n'existe pas. Le montant vit
-- dans `scenarios.resultats`, sur le scénario retenu.
